export * from './admin.service';
import { AdminService } from './admin.service';
export * from './applications.service';
import { ApplicationsService } from './applications.service';
export * from './businessCapabilities.service';
import { BusinessCapabilitiesService } from './businessCapabilities.service';
export * from './config.service';
import { ConfigService } from './config.service';
export * from './dataProducts.service';
import { DataProductsService } from './dataProducts.service';
export * from './entity.service';
import { EntityService } from './entity.service';
export * from './facets.service';
import { FacetsService } from './facets.service';
export * from './git.service';
import { GitService } from './git.service';
export * from './iTComponents.service';
import { ITComponentsService } from './iTComponents.service';
export * from './leanIX.service';
import { LeanIXService } from './leanIX.service';
export * from './platforms.service';
import { PlatformsService } from './platforms.service';
export * from './userGroups.service';
import { UserGroupsService } from './userGroups.service';
export const APIS = [AdminService, ApplicationsService, BusinessCapabilitiesService, ConfigService, DataProductsService, EntityService, FacetsService, GitService, ITComponentsService, LeanIXService, PlatformsService, UserGroupsService];
