/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUser201Response { 
    username?: string;
    /**
     * The password - shown only once
     */
    password?: string;
    isAdmin?: boolean;
    repositories?: { [key: string]: Array<string>; };
}
