/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneratePassword200Response { 
    username?: string;
    /**
     * The new password - shown only once
     */
    password?: string;
}

