/**
 * L8er API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitBranches200ResponseRepositoriesInner } from './gitBranches200ResponseRepositoriesInner';


export interface GitBranches200Response { 
    success?: boolean;
    repositories?: Array<GitBranches200ResponseRepositoriesInner>;
}

