/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitBranches200ResponseRepositoriesInner } from './gitBranches200ResponseRepositoriesInner';


export interface GitBranches200Response { 
    success?: boolean;
    /**
     * Default repository name from server config
     */
    defaultRepo?: string;
    /**
     * Default branch name from server config
     */
    defaultBranch?: string;
    repositories?: Array<GitBranches200ResponseRepositoriesInner>;
}

