/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitBranches200ResponseRepositoriesInnerBranchesInner { 
    name?: string;
    /**
     * True if branch directory exists locally
     */
    isCloned?: boolean;
    hasUncommittedChanges?: boolean;
    /**
     * True if this branch directory is inside a Git work tree
     */
    isGitControlled?: boolean;
}

