/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitCommitAndPushRepoBranch200Response { 
    success?: boolean;
    message?: string;
    output?: string | null;
    error?: string | null;
}

