/**
 * L8er API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitCommitAndPushRequest { 
    message?: string;
    /**
     * Repository name (optional)
     */
    repoName?: string;
    /**
     * Branch name (optional)
     */
    branch?: string;
}

