/**
 * L8er API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitClone200Response { 
    success?: boolean;
    message?: string;
    output?: string | null;
    error?: string | null;
    /**
     * Repository name (for frontend to set selected repo)
     */
    repoName?: string;
    /**
     * Default branch name (e.g. main or master)
     */
    defaultBranch?: string;
}

