/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitFileHistory200ResponseEntriesInner } from './gitFileHistory200ResponseEntriesInner';


export interface GitFileHistory200Response { 
    success?: boolean;
    entries?: Array<GitFileHistory200ResponseEntriesInner>;
    message?: string | null;
}

