/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitFileHistory200ResponseEntriesInner { 
    hash?: string;
    shortHash?: string;
    date?: string;
    message?: string;
}

