/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListUsers200ResponseUsersInner } from './listUsers200ResponseUsersInner';


export interface ListUsers200Response { 
    users?: Array<ListUsers200ResponseUsersInner>;
}

