/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListUsers200ResponseUsersInner { 
    username?: string;
    access?: boolean;
    isAdmin?: boolean;
    repositories?: { [key: string]: Array<string>; };
}
