/**
 * L8er API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListEntities200ResponseInnerRelApplicationToUserGroupInner } from './listEntities200ResponseInnerRelApplicationToUserGroupInner';


export interface ListEntities200ResponseInner { 
    id?: string;
    displayName?: string;
    /**
     * Application description (top-level field in Application JSON).
     * May be null / missing depending on backend projection.
     */
    description?: string | null;
    type?: string;
    earmarkingsTEMP?: string | null;
    lxTimeClassification?: string | null;
    lxTimeClassificationDescription?: string | null;
    functionalSuitability?: string | null;
    technicalSuitability?: string | null;
    businessCriticality?: string | null;
    /**
     * From entity JSON
     */
    aggregatedObsolescenceRisk?: any | null;
    platformTEMP?: string | null;
    relApplicationToUserGroup?: Array<ListEntities200ResponseInnerRelApplicationToUserGroupInner>;
    relApplicationToBusinessCapability?: Array<ListEntities200ResponseInnerRelApplicationToUserGroupInner>;
    /** Migration targets: array of { id, type?, displayName, lifecycle?, proportion?, priority?, effort?, eta? } from entity JSON (edges notation). Edge attributes lifecycle, proportion, priority, effort, eta stored alongside node. */
    migrationTarget?: Array<{
      id: string;
      type?: string;
      displayName: string;
      lifecycle?: string | null;
      proportion?: number | null;
      priority?: number | null;
      effort?: string | null;
      eta?: string | null;
    }> | null;
    /** Application lifecycle from entity JSON (ApplicationLifecycle.asString). */
    ApplicationLifecycle?: { asString?: string | null } | null;
}

