/*
 * Copyright (C) 2026 BrainBoutique Solutions GmbH (Wilko Hein)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <https://www.gnu.org>.
 */

/**
 * L8er API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListEntities200ResponseInnerRelApplicationToUserGroupInner } from './listEntities200ResponseInnerRelApplicationToUserGroupInner';


export interface ListEntities200ResponseInner { 
    id?: string;
    displayName?: string;
    /**
     * Application description (top-level field in Application JSON).
     * May be null / missing depending on backend projection.
     */
    description?: string | null;
    type?: string;
    earmarkingsTEMP?: string | null;
    lxTimeClassification?: string | null;
    lxTimeClassificationDescription?: string | null;
    functionalSuitability?: string | null;
    technicalSuitability?: string | null;
    businessCriticality?: string | null;
    /**
     * From entity JSON
     */
    aggregatedObsolescenceRisk?: any | null;
    platformTEMP?: string | null;
    relApplicationToUserGroup?: Array<ListEntities200ResponseInnerRelApplicationToUserGroupInner>;
    relApplicationToBusinessCapability?: Array<ListEntities200ResponseInnerRelApplicationToUserGroupInner>;
    relApplicationToDataProduct?: Array<ListEntities200ResponseInnerRelApplicationToUserGroupInner>;
    /** Migration targets: array of { id, type?, displayName, lifecycle?, proportion?, priority?, effort?, eta? } from entity JSON (edges notation). Edge attributes lifecycle, proportion, priority, effort, eta stored alongside node. */
    migrationTarget?: Array<{
      id: string;
      type?: string;
      displayName: string;
      lifecycle?: string | null;
      proportion?: number | null;
      priority?: number | null;
      effort?: string | null;
      eta?: string | null;
    }> | null;
    /** Alternative applications: array of { id, type?, displayName, functionalOverlap?, comment? } from entity JSON (edges notation). */
    alternatives?: Array<{
      id: string;
      type?: string;
      displayName: string;
      functionalOverlap?: number | null;
      comment?: string | null;
    }> | null;
    /** Application lifecycle from entity JSON (ApplicationLifecycle.asString). */
    ApplicationLifecycle?: { asString?: string | null } | null;
}

