/**
 * L8er API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListEntities200ResponseInnerRelApplicationToUserGroupInner { 
    id?: string;
    displayName?: string;
    fullName?: string;
    type?: string;
    category?: string;
    description?: string;
}

