/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserRequest { 
    role?: UpdateUserRequest.RoleEnum;
    read?: Array<string>;
    edit?: Array<string>;
}
export namespace UpdateUserRequest {
    export const RoleEnum = {
        User: 'user',
        Admin: 'admin'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


