/**
 * ZenEA API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUser200Response { 
    username?: string;
    role?: string;
    read?: Array<string>;
    edit?: Array<string>;
}

